version: '3.8'
services:
  postgis:
    image: postgis/postgis
    restart: always
    container_name: postgis-container
    env_file:
      .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - core-network

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - '5050:80'
    env_file:
      .env
    links:
      - postgis
    networks:
      - core-network

volumes:
  db:
    driver: local

networks:
  core-network:
    driver: bridge