version: '3.8'
services:
  geoapi_svc:
    image: andruxa17/${APP_NAME}:${TAG}
    container_name: geoapi-container
    restart: always
    depends_on:
      - postgis_svc
    env_file:
      .env
    ports:
      - "80:80"
    networks:
      - core-network

  postgis_svc:
    image: postgis/postgis
    restart: always
    container_name: postgis-container
    env_file:
      .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - core-network

  pgadmin4_svc:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - '5050:80'
    env_file:
      .env
    links:
      - postgis_svc
    networks:
      - core-network

volumes:
  db:
    driver: local

networks:
  core-network:
    driver: bridge